# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  raytrace_config = debug

else ifeq ($(config),development)
  raytrace_config = development

else ifeq ($(config),release)
  raytrace_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := raytrace

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

raytrace:
ifneq (,$(raytrace_config))
	@echo "==== Building raytrace ($(raytrace_config)) ===="
	@${MAKE} --no-print-directory -C src -f Makefile config=$(raytrace_config)
endif

clean:
	@${MAKE} --no-print-directory -C src -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  development"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   raytrace"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"